-- Insert sample profiles (these will be created after users sign up)
-- This is just for reference - actual data will be created through the app

-- Sample mentor profiles that could be created:
/*
INSERT INTO profiles (id, email, name, college, bio, skills, hourly_rate, is_available, rating, total_sessions) VALUES
('11111111-1111-1111-1111-111111111111', 'john@example.com', 'John Doe', 'MIT', 'Full-stack developer with 3 years of experience', ARRAY['JavaScript', 'React', 'Node.js'], 25, true, 4.8, 15),
('22222222-2222-2222-2222-222222222222', 'jane@example.com', 'Jane Smith', 'Stanford', 'UI/UX designer passionate about creating beautiful interfaces', ARRAY['UI/UX Design', 'Figma', 'Photoshop'], 30, true, 4.9, 22),
('33333333-3333-3333-3333-333333333333', 'mike@example.com', 'Mike Johnson', 'Harvard', 'Data scientist and machine learning enthusiast', ARRAY['Python', 'Data Science', 'Machine Learning'], 35, true, 4.7, 18);
*/

-- Note: In a real application, these profiles would be created when users sign up through Google OAuth
-- The IDs would be generated by Supabase Auth, not manually inserted